### PR TITLE
Add Unset env feature to deactivate propery

### PR DESCRIPTION
**Pull request by ArmCorelin**
Changed to  use unset and set command when env-update.
Because conda is now using those command and I couldn't deactivate without it.

I checked it with ;
$ conda shell.posix deactivate

### CODE REVIEW

**Comment by sambrightman** [comment]
The second parameter to `setenv` should be `nil` (or omitted) to unset properly. That said, any chance of getting a release with this PR merged?

**Comment by ArmCorelin** [comment]
@sambrightman Hi, Actually I was aware this is caused conda script is using not only export, using set and unset also. If you need this work immediately, please use my repo.
Thanks.

**Comment by sambrightman** [comment]
The question about releasing was for @necaris.

@ArmCorelin you should adjust the `setenv` parameter as described.

**Comment by ArmCorelin** [comment]
@sambrightman OK, I will change that line to 
 (setenv (format "%s" arg) nil))
Thanks

**Comment by necaris** [comment]
Merged -- apologies for delay!

**Pull request merged**
