### PR TITLE
Update activation command, auto-format

### PR DESCRIPTION
**Pull request by necaris**
Replace the previous "source activate" with "conda activate" -- see #54  

- [ ] maintain backwards compatibility with older Conda versions. This requires knowing the active Conda version somehow.
- [ ] ensure the shell spawned is set up for `conda activate` -- do we have to ensure that `conda init` is run in every shell?

----

#

### CODE REVIEW

**Comment by bestlem** [comment]
Any progress on this?

I note that `conda -V env list` produces `conda 4.9.2` but I have no idea what earlier ones do

shell set up - I suspect yes. but is a nuicancs as much shell is used for compiling etc so no need for conda. conda.el should not try to run on every shell.

**Comment by jinschoi** [comment]
"source activate" requires CONDAHOME/bin to be in your path, which is where the file "activate" lives and will be found by source. More recent versions of anaconda do not include that directory in your path when it is set up with conda init. You could handle backward compatibility by explicitly giving the full path to activate to source.

4.4.0 was released over three years ago, so I would think most people have switched to using conda activate by now. It is the recommended way for people to switch environments.

I have overridden this for myself in .emacs (just changing "source" to "conda"), and it works fine.

**Comment by jinschoi** [comment]
Also, if you want to run a version check, conda -V (or /usr/local/anaconda3/bin/conda -V) outputs "conda 4.9.2".
Regarding your second point, I would say that it's up to the user to have set up conda to run properly in their shells, not the responsibility of conda.el.

**Comment by necaris** [comment]
@jinschoi considering that a lot of people rarely update `conda` I would not be surprised if lots of folks are using older Anaconda versions. However, you're right that it's been long enough that it's not unreasonable to switch over by default, and see if folks complain (we can restore previous behavior after a version check if so).

**Pull request merged**
