### PR TITLE
Stop using `conda ..activate`

### PR DESCRIPTION
**Pull request by necaris**
As of 4.6.0, this emits deprecation warnings -- remove it in favor of simple concatenation for now.

### CODE REVIEW

**Comment by jlstevens** [comment]
I don't know how I missed this PR! My workaround for this issue is in #24 to address #22.

I'm glad to learn you are already aware of this problem!

**Comment by jlstevens** [comment]
Another (temporary) fix on Unix might be this as the warnings are sent to `stderr` only:

```
conda ..activate bash nei 2> /dev/null
```

But it is probably better to avoid the deprecated pathway altogether.

**Comment by jlstevens** [comment]
I believe the approach currently used in this PR (concatenating `"bin"`) won't work on Windows...

**Comment by jlstevens** [comment]
I talked to one of the conda developers and I was told that 1) there isn't a clean replacement right now for that particular use case and 2) that the conda subcommands starting with `..` were always meant to be private.

The best suggestion I got was to write some type of `JSONActivator` in `conda/activate.py` (i.e in conda itself) to make this information available as JSON output that can be easily parsed. I would be happy to look into this approach, but it would mean that `conda.el` will require newer conda versions (assuming the necessary PRs got merged and released).

Perhaps one plan might be to use the approach shown in #24 which is definitely a hack (but does have the advantage that it should also work on windows?) to support conda version 4.6.1. Then maybe we could try to move to the `JSONActivator` approach in future?

**Comment by necaris** [comment]
That's one way to approach it, sure. Let me see what that might involve

**Comment by calizarr** [comment]
Just noticed this PR as I was typing out my comment in the other issue. If the solution I posted in the issue works for Linux/OSX as well this may work but it's only valid for conda 4.6+

https://github.com/necaris/conda.el/issues/22#issuecomment-490077259

**Comment by necaris** [comment]
@jlstevens note that I've tried to implement the feature [you described](https://github.com/necaris/conda.el/pull/23#issuecomment-464786560) in `conda` [here](https://github.com/conda/conda/pull/8727) as a step in the right direction.

**Comment by necaris** [comment]
(NOTE: doesn't seem to work, right now)

**Review by necaris — COMMENTED** [review]
bors merge

**Comment by necaris** [comment]
@jinschoi after merging your PR #108 can you confirm this branch works for you? I'd like one more pair of eyes before I merge as "works on my machine" ;-)

**Comment by jinschoi** [comment]
Yes. I'm running the fix/deprecated-conda-activate-command branch except I have mine merged back up to the main branch, and I can switch envs without a problem. Thanks for the pull.

**Pull request merged**
