### PR TITLE
Fix a bug that was breaking shell-strip-env

### PR DESCRIPTION
**Pull request by monomon**
* assume passed buffer name would be first arg in &rest
* Fix activate on windows - do not use "source", and add a newline to
  the command
* Replace an ad-do-it with (apply orig-fun...) - seems like advice-add
  doesn't provide ad-do-it?

### CODE REVIEW

**Comment by necaris** [comment]
@monomon Thank you so much for this PR! I've been trying to figure out how best to replicate #10 -- I don't use Windows, and honestly don't use `eshell` much, so this hadn't bit me before.

Elisp code looks good -- Indeed, `advice-add` doesn't provide `ad-do-it`, that's the legacy function-advice model that I copied over from `virtualenv.el` and missed updating when I moved over to `advice-add`... 😥 

Looking at other best-practices, it seems sending a newline after the activate command doesn't hurt on any OS, so it might be worth factoring that out into a separate call that's sent regardless of the OS. Otherwise, this looks great, thank you again @monomon !

**Comment by JoshOBrien** [comment]
@monomon Thanks! I can confirm that your patch fixes the problem I reported on my Windows 7 machine. I really appreciate your (and @necaris ') contributions.

**Comment by necaris** [comment]
@monomon the CI is failing because there aren't actually any useful tests -- I've got a branch I'm working on to add tests, hoping to have this working as expected this weekend. In the meantime I'll go ahead and merge this PR, looking forward to more bugs you report on Windows!

**Review by necaris — COMMENTED** [review]
Beans!

**Review by necaris — CHANGES_REQUESTED** [review]
Beans!

**Review by necaris — APPROVED** [review]
Beans!

**Review by necaris — COMMENTED** [review]
Warmed-up beans?

**Review by necaris — CHANGES_REQUESTED** [review]
Please warm up the beans.

**Review by necaris — APPROVED** [review]
Beans look nice and warm, good show!

**Review by necaris — APPROVED** [review]
Cooled down beans!

**Review by necaris — CHANGES_REQUESTED** [review]
Beans need to cool down

**Pull request merged**
